name: CI

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t x-ray-disease-detection .
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "arcane-thicket-47996"
          heroku_email: "larry.goyeau@gmail.com"
          usedocker: true